// Puzzle bank — Wheel of Cyber Fortune
// Phrases may contain A-Z, spaces, and the literal characters & and -
// (& and - render as always-visible static tiles).
"use strict";

const PUZZLES = [
  // ── TECHNOLOGY ──────────────────────────────────────────────
  { cat: "TECHNOLOGY", text: "ZERO TRUST ARCHITECTURE" },
  { cat: "TECHNOLOGY", text: "PUBLIC KEY INFRASTRUCTURE" },
  { cat: "TECHNOLOGY", text: "MULTIFACTOR AUTHENTICATION" },
  { cat: "TECHNOLOGY", text: "INTRUSION DETECTION SYSTEM" },
  { cat: "TECHNOLOGY", text: "NEXT GENERATION FIREWALL" },
  { cat: "TECHNOLOGY", text: "VIRTUAL PRIVATE NETWORK" },
  { cat: "TECHNOLOGY", text: "ENDPOINT DETECTION AND RESPONSE" },
  { cat: "TECHNOLOGY", text: "HARDWARE SECURITY MODULE" },
  { cat: "TECHNOLOGY", text: "TRUSTED PLATFORM MODULE" },
  { cat: "TECHNOLOGY", text: "FULL DISK ENCRYPTION" },
  { cat: "TECHNOLOGY", text: "WEB APPLICATION FIREWALL" },
  { cat: "TECHNOLOGY", text: "QUANTUM KEY DISTRIBUTION" },
  { cat: "TECHNOLOGY", text: "BIOMETRIC AUTHENTICATION" },
  { cat: "TECHNOLOGY", text: "AIR GAPPED NETWORK" },

  // ── TOOLS ───────────────────────────────────────────────────
  { cat: "TOOLS", text: "BURP SUITE" },
  { cat: "TOOLS", text: "METASPLOIT FRAMEWORK" },
  { cat: "TOOLS", text: "WIRESHARK PACKET ANALYZER" },
  { cat: "TOOLS", text: "NMAP NETWORK SCANNER" },
  { cat: "TOOLS", text: "PFSENSE FIREWALL" },
  { cat: "TOOLS", text: "JOHN THE RIPPER" },
  { cat: "TOOLS", text: "HASHCAT PASSWORD CRACKER" },
  { cat: "TOOLS", text: "KALI LINUX" },
  { cat: "TOOLS", text: "GHIDRA REVERSE ENGINEERING" },
  { cat: "TOOLS", text: "SNORT INTRUSION DETECTION" },
  { cat: "TOOLS", text: "MIMIKATZ" },
  { cat: "TOOLS", text: "COBALT STRIKE" },
  { cat: "TOOLS", text: "NESSUS VULNERABILITY SCANNER" },
  { cat: "TOOLS", text: "SPLUNK ENTERPRISE SECURITY" },
  { cat: "TOOLS", text: "SHODAN SEARCH ENGINE" },

  // ── CONCEPTS ────────────────────────────────────────────────
  { cat: "CONCEPTS", text: "DEFENSE IN DEPTH" },
  { cat: "CONCEPTS", text: "PRINCIPLE OF LEAST PRIVILEGE" },
  { cat: "CONCEPTS", text: "SOCIAL ENGINEERING" },
  { cat: "CONCEPTS", text: "SPEAR PHISHING CAMPAIGN" },
  { cat: "CONCEPTS", text: "KERBEROASTING" },
  { cat: "CONCEPTS", text: "SQL INJECTION ATTACK" },
  { cat: "CONCEPTS", text: "CROSS SITE SCRIPTING" },
  { cat: "CONCEPTS", text: "BUFFER OVERFLOW ATTACK" },
  { cat: "CONCEPTS", text: "MAN IN THE MIDDLE ATTACK" },
  { cat: "CONCEPTS", text: "SUPPLY CHAIN ATTACK" },
  { cat: "CONCEPTS", text: "RANSOMWARE AS A SERVICE" },
  { cat: "CONCEPTS", text: "PRIVILEGE ESCALATION" },
  { cat: "CONCEPTS", text: "LATERAL MOVEMENT" },
  { cat: "CONCEPTS", text: "THREAT HUNTING" },
  { cat: "CONCEPTS", text: "ZERO DAY EXPLOIT" },
  { cat: "CONCEPTS", text: "SECURITY THROUGH OBSCURITY" },
  { cat: "CONCEPTS", text: "PASS THE HASH ATTACK" },

  // ── FRAMEWORKS ──────────────────────────────────────────────
  { cat: "FRAMEWORKS", text: "MITRE ATT&CK" },
  { cat: "FRAMEWORKS", text: "NIST CYBERSECURITY FRAMEWORK" },
  { cat: "FRAMEWORKS", text: "OWASP TOP TEN" },
  { cat: "FRAMEWORKS", text: "CIS CRITICAL SECURITY CONTROLS" },
  { cat: "FRAMEWORKS", text: "CYBER KILL CHAIN" },
  { cat: "FRAMEWORKS", text: "DIAMOND MODEL OF INTRUSION ANALYSIS" },
  { cat: "FRAMEWORKS", text: "GENERAL DATA PROTECTION REGULATION" },
  { cat: "FRAMEWORKS", text: "ZERO TRUST MATURITY MODEL" },
  { cat: "FRAMEWORKS", text: "SHARED RESPONSIBILITY MODEL" },
  { cat: "FRAMEWORKS", text: "STRIDE THREAT MODEL" },
  { cat: "FRAMEWORKS", text: "COMMON VULNERABILITY SCORING SYSTEM" },
  { cat: "FRAMEWORKS", text: "FEDRAMP AUTHORIZATION" },
  { cat: "FRAMEWORKS", text: "PCI DATA SECURITY STANDARD" },

  // ── PEOPLE & COMPANIES ──────────────────────────────────────
  { cat: "PEOPLE & COMPANIES", text: "KEVIN MITNICK" },
  { cat: "PEOPLE & COMPANIES", text: "BRUCE SCHNEIER" },
  { cat: "PEOPLE & COMPANIES", text: "CROWDSTRIKE FALCON" },
  { cat: "PEOPLE & COMPANIES", text: "PALO ALTO NETWORKS" },
  { cat: "PEOPLE & COMPANIES", text: "CHECK POINT SOFTWARE" },
  { cat: "PEOPLE & COMPANIES", text: "RECORDED FUTURE" },
  { cat: "PEOPLE & COMPANIES", text: "MANDIANT THREAT INTELLIGENCE" },
  { cat: "PEOPLE & COMPANIES", text: "KATIE MOUSSOURIS" },
  { cat: "PEOPLE & COMPANIES", text: "DAN KAMINSKY" },
  { cat: "PEOPLE & COMPANIES", text: "TROY HUNT" },
  { cat: "PEOPLE & COMPANIES", text: "HAVE I BEEN PWNED" },
  { cat: "PEOPLE & COMPANIES", text: "SENTINELONE" },
  { cat: "PEOPLE & COMPANIES", text: "LOCKHEED MARTIN" },
  { cat: "PEOPLE & COMPANIES", text: "WHITFIELD DIFFIE" },
];
